Solution for Q.NO.1

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('Target_values.csv')

In [4]:
n = len(data.values)
new_data = data.values
categorical = np.zeros((n,n), dtype = float)


In [5]:
def conversion(data):
  n = len(data.values)
  new_data = data.values
  categorical = np.zeros((n,n), dtype = float)
  for i in range(n):
    categorical[[i],new_data[i]] = 1
  return categorical


In [6]:
a = conversion(data)
a


array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

Solution to Q.no 2

In [7]:
data1 = pd.read_csv('Input_to_softmax.csv')

In [8]:
import math

def conversion1(data1):
  x = len(data1.values)
  y = len(data1.values[0])
  new_data1 = data1.values
  categorical = np.zeros((x,y), dtype = float) 
  for i in range(x):
    summation = 0

    for sum in range(y):
      summation += math.exp(new_data1[i][sum])

    for j in range(y):
      value = math.exp(new_data1[i][j])/summation
      categorical[[i],[j]] = value

  return categorical

categorical2 = conversion1(data1)
categorical2

array([[0.03192011, 0.2358595 , 0.08676786, 0.00431992, 0.6411326 ],
       [0.01105439, 0.08168151, 0.60354924, 0.22203336, 0.08168151],
       [0.59229879, 0.21789455, 0.08015892, 0.02948882, 0.08015892],
       [0.34829927, 0.12813214, 0.12813214, 0.34829927, 0.04713718],
       [0.02591887, 0.19151597, 0.19151597, 0.52059439, 0.07045479],
       [0.19151597, 0.07045479, 0.52059439, 0.02591887, 0.19151597],
       [0.07629314, 0.56373431, 0.20738626, 0.07629314, 0.07629314],
       [0.24760201, 0.03350929, 0.67305204, 0.03350929, 0.01232738],
       [0.06745081, 0.49839779, 0.06745081, 0.1833503 , 0.1833503 ],
       [0.06745081, 0.06745081, 0.49839779, 0.1833503 , 0.1833503 ]])

SOLUTION TO Q.NO 3

In [9]:
a_new = a[0:11,0:5]
a_new

array([[0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [12]:
 import math
 def calculate_error(a_new , categorical2):

   categorical_new = np.zeros((10,1), dtype = float) 
   
   for row in range(10):
     rowError = 0
     for column in range(5):
       print('Row', row)
       print('Column', column)
       predValue = categorical2[row][column]
       targetValue = a_new[row][column]
       error = targetValue*(math.log(predValue, 10))
       print(predValue)
       print(targetValue)
       print(error)
       rowError += error
     categorical_new[[row],[0]] = -(rowError)
     
       
   return categorical_new

calculate_error(a_new, categorical2)
          




Row 0
Column 0
0.03192011275871308
0.0
-0.0
Row 0
Column 1
0.23585950385832297
0.0
-0.0
Row 0
Column 2
0.0867678624743735
0.0
-0.0
Row 0
Column 3
0.0043199175011450494
0.0
-0.0
Row 0
Column 4
0.6411326034074454
1.0
-0.19305213745113967
Row 1
Column 0
0.011054389912094145
0.0
-0.0
Row 1
Column 1
0.08168150719991668
1.0
-1.0878762571776617
Row 1
Column 2
0.6035492389453923
0.0
-0.0
Row 1
Column 3
0.2220333567426802
0.0
-0.0
Row 1
Column 4
0.08168150719991668
0.0
-0.0
Row 2
Column 0
0.5922987857150971
1.0
-0.22745915771491224
Row 2
Column 1
0.21789454629539376
0.0
-0.0
Row 2
Column 2
0.08015892392545443
0.0
-0.0
Row 2
Column 3
0.029488820138600335
0.0
-0.0
Row 2
Column 4
0.08015892392545443
0.0
-0.0
Row 3
Column 0
0.3482992693129455
0.0
-0.0
Row 3
Column 1
0.1281321405552681
0.0
-0.0
Row 3
Column 2
0.1281321405552681
0.0
-0.0
Row 3
Column 3
0.3482992693129455
1.0
-0.4580474366347543
Row 3
Column 4
0.04713718026357273
0.0
-0.0
Row 4
Column 0
0.025918868635908747
0.0
-0.0
Row 4
Column 1
0.1

array([[0.19305214],
       [1.08787626],
       [0.22745916],
       [0.45804744],
       [0.28350051],
       [0.28350051],
       [1.1175145 ],
       [0.60624584],
       [0.30242389],
       [0.30242389]])